
import { AlienSubtype, Card, Faction, TowerType, SpecialAbilityBlueprint, UnitType, TargetPreference, SpellShape, VisualFamily } from './types';

export const ARENA_WIDTH = 1200;
export const ARENA_HEIGHT = 675;
export const MAX_ENERGY = 10;
// Energía ganada por segundo (se multiplica por deltaTime en segundos).
export const BASE_ENERGY_GAIN_RATE = 0.9;
export const GAME_DURATION = 180; // 3 minutos en segundos
export const BRIDGE_X = ARENA_WIDTH / 2;
export const BRIDGE_TOP_Y = ARENA_HEIGHT / 2 - 190;
export const BRIDGE_BOTTOM_Y = ARENA_HEIGHT / 2 + 190;
export const BRIDGE_GAP_HALF = 100;

export const POST_GAME_SUGGESTION_CONFIG = {
  underusedThreshold: 1,
  highAverageCost: 4.5,
  maxSuggestions: 3,
  cheaperCostBuffer: 1
};

type CardSeed = Omit<Card, 'visualFamily' | 'spellShape'> & Partial<Pick<Card, 'visualFamily' | 'spellShape'>>;

const VISUAL_FAMILY_BY_FACTION: Record<Faction, VisualFamily> = {
  [Faction.HUMAN]: 'humano',
  [Faction.ANDROID]: 'ciber',
  [Faction.ALIEN]: 'organico'
};

const SPELL_SHAPES: Record<string, SpellShape> = {
  orbital_laser: 'concentric',
  healing_matrix: 'runes',
  android_selective_empulse: 'concentric',
  android_temporal_overclock: 'runes',
  aracnid_spore_rain: 'concentric',
  aracnid_pheromone_cloud: 'runes',
  humanoid_psychic_silence: 'runes',
  humanoid_fear_wave: 'concentric',
  slimoid_viscous_wave: 'portal',
  slimoid_corrosive_shroud: 'portal'
};

export const MOTHERSHIP_BALANCE = {
  cost: 8,
  hpRatioFromOuter: 0.625,
  speed: 0.55,
  collisionRadius: 30,
  damage: 0,
  range: 0,
  attackSpeed: 5000,
  baseCooldownMs: 30000,
  payloadBaseIntervalMs: 7000,
  payloadIntervalPerCostMs: 1000,
  color: '#9ae6ff' as const
};

export const EMP_ABILITY_BALANCE = {
  cost: 3,
  radius: 260,
  cooldownMs: 24000,
  defaultMode: 'lockdown',
  modes: {
    lockdown: {
      key: 'lockdown',
      label: 'Modo 1 · Apagón total',
      description: 'Aturde al máximo sin aplicar daño.',
      stunDuration: 3600,
      damage: 0
    },
    disruptor: {
      key: 'disruptor',
      label: 'Modo 2 · Disrupción',
      description: 'Aturde menos tiempo pero inflige daño ligero.',
      stunDuration: 1800,
      damage: 70
    }
  }
} as const;

export const ARACNO_SPIDER_MODES = {
  lethal: {
    hp: 360,
    damage: 54,
    speed: 1.85,
    range: 26,
    attackSpeed: 900,
    targetPref: TargetPreference.ANY
  },
  healing: {
    hp: 380,
    damage: -32,
    speed: 1.6,
    range: 70,
    attackSpeed: 1050,
    targetPref: TargetPreference.ALLIES
  },
  kamikaze: {
    hp: 320,
    damage: 68,
    speed: 2,
    range: 18,
    attackSpeed: 750,
    targetPref: TargetPreference.ANY,
    dotDuration: 2600
  }
} as const;

const CARD_SEEDS: CardSeed[] = [
  {
    id: 'infantry',
    name: 'Guardia de Vanguardia',
    cost: 2,
    type: UnitType.GROUND,
    faction: Faction.HUMAN,
    hp: 480,
    damage: 38,
    speed: 1.2,
    range: 28,
    attackSpeed: 1100,
    targetPref: TargetPreference.ANY,
    description: 'Escudos cinéticos al frente. Tapa ráfagas iniciales y remata enjambres cuerpo a cuerpo.',
    flavor: '“Avanzamos por reflejo: escudo arriba, cabeza abajo, moral intacta.”',
    count: 3,
    shape: 'square',
    color: '#3ba7d5',
    projectileType: 'none'
  },
  {
    id: 'marines',
    name: 'Duelos Élite',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.HUMAN,
    hp: 360,
    damage: 60,
    speed: 1.6,
    range: 24,
    attackSpeed: 900,
    targetPref: TargetPreference.ANY,
    description: 'Espadas dobles para cortar líneas blandas y presionar tanques lentos a corta distancia.',
    flavor: '“Dos hojas, cero dudas.”',
    count: 2,
    shape: 'triangle',
    color: '#1f8a70',
    projectileType: 'none'
  },
  {
    id: 'guardian',
    name: 'Abanderado de Moral',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.HUMAN,
    hp: 540,
    damage: -45,
    speed: 1.3,
    range: 80,
    attackSpeed: 1200,
    targetPref: TargetPreference.ALLIES,
    description: 'Lanza curas de cercanía y mantiene la línea unida. Neutraliza daño de desgaste y castiga AOE prolongado.',
    flavor: '“Si oyes el cuerno, aún podemos resistir.”',
    count: 1,
    shape: 'diamond',
    color: '#f2c14f',
    projectileType: 'none'
  },
  {
    id: 'fighter',
    name: 'Caza de Apoyo',
    cost: 4,
    type: UnitType.AIR,
    faction: Faction.HUMAN,
    hp: 520,
    damage: 44,
    speed: 2.2,
    range: 190,
    attackSpeed: 850,
    targetPref: TargetPreference.ANY,
    description: 'Ráfagas de cohetes de rango medio que dispersan masas y frenan pushes ligeros.',
    flavor: '“Si lo ves, ya está marcado.”',
    count: 1,
    isAoE: true,
    aoeRadius: 60,
    shape: 'hexagon',
    color: '#ff914d',
    projectileType: 'missile'
  },
  {
    id: 'sky_lancer_wing',
    name: 'Ala Lancera',
    cost: 3,
    type: UnitType.AIR,
    faction: Faction.HUMAN,
    hp: 430,
    damage: 36,
    speed: 2.5,
    range: 170,
    attackSpeed: 800,
    targetPref: TargetPreference.ANY,
    description: 'Escuadra ágil que limpia globos y castiga pushes ligeros. Débil a AA fija y ráfagas de plasma.',
    flavor: '“Aparecemos, perforamos y nos vamos antes de escuchar el eco.”',
    count: 2,
    shape: 'diamond',
    color: '#66c8ff',
    projectileType: 'laser'
  },
  {
    id: 'aegis_gunship',
    name: 'Gunship Égida',
    cost: 5,
    type: UnitType.AIR,
    faction: Faction.HUMAN,
    hp: 920,
    damage: 78,
    speed: 1.7,
    range: 210,
    attackSpeed: 950,
    targetPref: TargetPreference.ANY,
    description: 'Plataforma de apoyo aéreo con microtaunts y bombardeo en área. Excelente para estabilizar pushes medianos.',
    flavor: '“Si escuchas su ronroneo, es que sigues a salvo.”',
    count: 1,
    isAoE: true,
    aoeRadius: 55,
    shape: 'circle',
    color: '#4fb3ff',
    projectileType: 'plasma'
  },
  {
    id: 'nova_squad',
    name: 'Escuadra Nova',
    cost: 5,
    type: UnitType.GROUND,
    faction: Faction.HUMAN,
    hp: 410,
    damage: 95,
    speed: 1,
    range: 250,
    attackSpeed: 1700,
    targetPref: TargetPreference.ANY,
    description: 'Francotiradores con disparo de carga: abren huecos en tanques y estructuras, pero necesitan protección.',
    flavor: '“Respira, apunta, desaparece.”',
    count: 2,
    shape: 'star',
    color: '#9c7bff',
    projectileType: 'beam'
  },
  {
    id: 'iron_star_tank',
    name: 'Tanque Estrella de Hierro',
    cost: 6,
    type: UnitType.GROUND,
    faction: Faction.HUMAN,
    hp: 1500,
    damage: 90,
    speed: 0.6,
    range: 140,
    attackSpeed: 1400,
    targetPref: TargetPreference.ANY,
    description: 'Blindaje grueso y sistemas de ruido activo. Provoke/taunt natural para absorber fuego enemigo.',
    flavor: '“Si no disparan al tanque, algo anda mal.”',
    count: 1,
    isAoE: true,
    aoeRadius: 70,
    shape: 'circle',
    color: '#6b7a8f',
    projectileType: 'plasma'
  },
  {
    id: 'tank',
    name: 'Búnker de Apoyo',
    cost: 4,
    type: UnitType.BUILDING,
    faction: Faction.HUMAN,
    hp: 1000,
    damage: 60,
    speed: 0,
    range: 200,
    attackSpeed: 900,
    targetPref: TargetPreference.ANY,
    description: 'Cobertura fija que refuerza pushes aliados y limpia hostigamiento cercano. Ideal contra enjambres terrestres.',
    flavor: '“Metal, sacos terreros y café recalentado: hogar temporal.”',
    count: 1,
    shape: 'square',
    color: '#8f9aa5',
    projectileType: 'plasma'
  },
  {
    id: 'skyfire_radar',
    name: 'Radar Skyfire',
    cost: 3,
    type: UnitType.BUILDING,
    faction: Faction.HUMAN,
    hp: 620,
    damage: 68,
    speed: 0,
    range: 260,
    attackSpeed: 1100,
    targetPref: TargetPreference.AIR,
    description: 'Estación AA especializada: derriba drones y cazas a larga distancia sin gastar tropas de línea.',
    flavor: '“Ojos en el cielo, gatillo ligero.”',
    count: 1,
    shape: 'triangle',
    color: '#5ad1e3',
    projectileType: 'laser'
  },
  {
    id: 'orbital_laser',
    name: 'Bombardeo Orbital',
    cost: 6,
    type: UnitType.SPELL,
    faction: Faction.HUMAN,
    hp: 1,
    damage: 280,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ANY,
    description: 'Golpe puntual de alta energía. Elimina blobs y reduce torres a quemaduras criticas.',
    flavor: '“No es apoyo. Es sentencia.”',
    count: 1,
    isAoE: true,
    aoeRadius: 120,
    shape: 'hexagon',
    color: '#ff4f70',
    projectileType: 'beam'
  },
  {
    id: 'healing_matrix',
    name: 'Aumento de Moral',
    cost: 3,
    type: UnitType.SPELL,
    faction: Faction.HUMAN,
    hp: 1,
    damage: -200,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ALLIES,
    description: 'Pulso de moral/velocidad: cura en área durante unos segundos y estabiliza pushes antes del cruce.',
    flavor: '“Segunda bocanada, segundo empuje.”',
    count: 1,
    isAoE: true,
    aoeRadius: 180,
    shape: 'circle',
    color: '#5ee290',
    projectileType: 'none'
  },
  {
    id: 'android_skystalker',
    name: 'Cazador Skystalker',
    cost: 3,
    type: UnitType.AIR,
    faction: Faction.ANDROID,
    hp: 360,
    damage: 52,
    speed: 2.6,
    range: 180,
    attackSpeed: 780,
    targetPref: TargetPreference.ANY,
    description: 'Dron interceptor con algoritmos de esquiva. Ideal para derribar globos o limpiar líneas blandas.',
    flavor: '“Si lo marcas, el dron ya lo persiguió.”',
    count: 3,
    shape: 'triangle',
    color: '#7ae6ff',
    projectileType: 'laser'
  },
  {
    id: 'android_orbital_piercer',
    name: 'Piercer Orbital',
    cost: 5,
    type: UnitType.AIR,
    faction: Faction.ANDROID,
    hp: 840,
    damage: 90,
    speed: 1.9,
    range: 240,
    attackSpeed: 1150,
    targetPref: TargetPreference.ANY,
    description: 'Fusiladora aérea con proyectiles penetrantes. Alcanza torres y tanques a distancia; vulnerable a torretas AA.',
    flavor: '“Órbitas bajas, impacto alto.”',
    count: 1,
    isAoE: false,
    shape: 'hexagon',
    color: '#5bd9ff',
    projectileType: 'beam'
  },
  {
    id: 'android_shock_blitzer',
    name: 'Asaltante Overclock',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ANDROID,
    hp: 520,
    damage: 62,
    speed: 1.65,
    range: 26,
    attackSpeed: 900,
    targetPref: TargetPreference.ANY,
    description: 'Dron de choque que se sobreclockea al entrar en contacto. Castiga líneas blandas pero sufre contra corrosión/napalm; resistencia innata a control biológico.',
    flavor: '“No corre: se proyecta a donde la chispa pueda saltar.”',
    count: 3,
    shape: 'triangle',
    color: '#7fd8f7',
    projectileType: 'none'
  },
  {
    id: 'android_arc_lancer',
    name: 'Lancero de Arco',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ANDROID,
    hp: 600,
    damage: 54,
    speed: 1.45,
    range: 32,
    attackSpeed: 1000,
    targetPref: TargetPreference.ANY,
    description: 'Descarga eléctrica que encadena brevemente a grupos cerrados. Aguanta control biológico pero se degrada rápido frente a corrosivos/napalm.',
    flavor: '“Dos picas: una para la carne, otra para los chips.”',
    count: 2,
    shape: 'square',
    color: '#74c7ff',
    projectileType: 'plasma'
  },
  {
    id: 'android_repair_enforcer',
    name: 'Enforcers Auto-reparables',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ANDROID,
    hp: 580,
    damage: 50,
    speed: 1.35,
    range: 24,
    attackSpeed: 950,
    targetPref: TargetPreference.ANY,
    description: 'Droides de contención que regeneran placas entre combates. Resistentes a control biológico pero débiles a corrosión/napalm que anula su pulido.',
    flavor: '“Si algo se rompe, se imprime una pieza sobre la marcha.”',
    count: 2,
    shape: 'diamond',
    color: '#6ad9cb',
    projectileType: 'none'
  },
  {
    id: 'android_optic_sniper',
    name: 'Tirador Óptico',
    cost: 5,
    type: UnitType.GROUND,
    faction: Faction.ANDROID,
    hp: 360,
    damage: 140,
    speed: 1.05,
    range: 280,
    attackSpeed: 1900,
    targetPref: TargetPreference.ANY,
    description: 'Sniper con lente óptica y marca de objetivo: rompe tanques y estructuras marcadas. Débil a corrosión/napalm pero inmune a control biológico.',
    flavor: '“Marca, calcula viento... y espera que nada oxide la lente.”',
    count: 1,
    shape: 'star',
    color: '#52e0ff',
    projectileType: 'laser'
  },
  {
    id: 'android_micro_missiles',
    name: 'Operador de Micro-misiles',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ANDROID,
    hp: 420,
    damage: 44,
    speed: 1.25,
    range: 210,
    attackSpeed: 780,
    targetPref: TargetPreference.ANY,
    description: 'Ráfagas de micro-misiles en cono corto: limpia enjambres y mantiene presión. Resistentes a bio-control; la corrosión y el napalm destrozan su chasis.',
    flavor: '“Doce tubos, cero tiempos muertos.”',
    count: 1,
    isAoE: true,
    aoeRadius: 55,
    shape: 'hexagon',
    color: '#60cfff',
    projectileType: 'missile'
  },
  {
    id: 'android_bulwark_mech',
    name: 'Mech Escudo Centinela',
    cost: 6,
    type: UnitType.GROUND,
    faction: Faction.ANDROID,
    hp: 1650,
    damage: 78,
    speed: 0.7,
    range: 140,
    attackSpeed: 1200,
    targetPref: TargetPreference.ANY,
    description: 'Modo centinela con taunt integrado: fija fuego enemigo mientras cubre pushes aliados. Resiste control biológico; la corrosión y el napalm drenan su blindaje.',
    flavor: '“Se planta, despliega escudo y decide que aquí termina el avance rival.”',
    count: 1,
    isAoE: true,
    aoeRadius: 65,
    shape: 'circle',
    color: '#5aa9ff',
    projectileType: 'plasma'
  },
  {
    id: 'android_modular_turret',
    name: 'Torreta Modular',
    cost: 4,
    type: UnitType.BUILDING,
    faction: Faction.ANDROID,
    hp: 1100,
    damage: 70,
    speed: 0,
    range: 220,
    attackSpeed: 850,
    targetPref: TargetPreference.ANY,
    description: 'Estructura que alterna entre modo ráfaga y modo rayo sostenido según la presión. Vulnerable a corrosión/napalm; casi inmune a control biológico.',
    flavor: '“Dos núcleos, un solo giro de muñeca.”',
    count: 1,
    shape: 'square',
    color: '#5fb7ff',
    projectileType: 'beam'
  },
  {
    id: 'android_energy_node',
    name: 'Nodo de Recarga',
    cost: 3,
    type: UnitType.BUILDING,
    faction: Faction.ANDROID,
    hp: 820,
    damage: -32,
    speed: 0,
    range: 160,
    attackSpeed: 1050,
    targetPref: TargetPreference.ALLIES,
    description: 'Generador estático que emite pulsos de energía para rearmar androides cercanos. Resiste control biológico; el napalm y la corrosión lo apagan enseguida.',
    flavor: '“Conecta, descarga y vuelve al frente.”',
    count: 1,
    shape: 'triangle',
    color: '#6fe3c6',
    projectileType: 'none'
  },
  {
    id: 'android_selective_empulse',
    name: 'Pulso EMP Selectivo',
    cost: 3,
    type: UnitType.SPELL,
    faction: Faction.ANDROID,
    hp: 1,
    damage: 130,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ANY,
    description: 'Explosión dirigida que aturde sistemas y limpia enjambres mecánicos sin afectar aliados. Resiste bio-control, pero su emisión es castigada por napalm/corrosión ambiental.',
    flavor: '“Silencio radial en un único pulso.”',
    count: 1,
    isAoE: true,
    aoeRadius: 170,
    shape: 'diamond',
    color: '#60f1ff',
    projectileType: 'beam'
  },
  {
    id: 'android_temporal_overclock',
    name: 'Sobrecarga Temporal',
    cost: 2,
    type: UnitType.SPELL,
    faction: Faction.ANDROID,
    hp: 1,
    damage: -180,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ALLIES,
    description: 'Overclock temporal que acelera androides cercanos y repara microfisuras. No afecta biología y sufre si el área está saturada de napalm/corrosión.',
    flavor: '“Todo rojo, todo verde: rendimiento o humo, no hay intermedio.”',
    count: 1,
    isAoE: true,
    aoeRadius: 150,
    shape: 'cross',
    color: '#72ffb5',
    projectileType: 'none'
  },
  {
    id: 'aracnid_light_swarm',
    name: 'Enjambre Ligero',
    cost: 2,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 260,
    damage: 32,
    speed: 1.6,
    range: 18,
    attackSpeed: 850,
    targetPref: TargetPreference.ANY,
    description: 'Mazos de zánganos cortadores: poco HP pero alto número. Se derriten con AOE o fuego concentrado.',
    flavor: '“Donde cae uno, tres más escalonarán la herida.”',
    count: 6,
    shape: 'triangle',
    color: '#c0f27c',
    projectileType: 'none'
  },
  {
    id: 'aracnid_venom_raider',
    name: 'Asaltante Venenoso',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 340,
    damage: 46,
    speed: 1.35,
    range: 20,
    attackSpeed: 900,
    targetPref: TargetPreference.ANY,
    description: 'Inyecta toxinas y desgasta tanques, pero su caparazón se quiebra ante napalm o salpicaduras AOE.',
    flavor: '“Sus colmillos dejan niebla; el fuego los borra.”',
    count: 5,
    shape: 'square',
    color: '#9cd67b',
    projectileType: 'none'
  },
  {
    id: 'aracnid_slowshell_charger',
    name: 'Cargador con Ralentización',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 420,
    damage: 52,
    speed: 1.4,
    range: 26,
    attackSpeed: 1000,
    targetPref: TargetPreference.ANY,
    description: 'Embestida resinosa que aplica frenado a su objetivo. Lento al girar y arde fácil ante lanzallamas o AOE.',
    flavor: '“Primero pega, luego pega más lento.”',
    count: 4,
    shape: 'diamond',
    color: '#7fbf5b',
    projectileType: 'none'
  },
  {
    id: 'aracnid_stinger_wing',
    name: 'Ala Aguijón',
    cost: 3,
    type: UnitType.AIR,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 340,
    damage: 44,
    speed: 2.4,
    range: 150,
    attackSpeed: 820,
    targetPref: TargetPreference.ANY,
    description: 'Moscas colmena con picadura corrosiva. Limpian tropas blandas pero caen ante ráfagas o AA dedicada.',
    flavor: '“Un zumbido verde, luego agujas.”',
    count: 5,
    shape: 'diamond',
    color: '#b0ff92',
    projectileType: 'plasma'
  },
  {
    id: 'aracnid_bile_carrier',
    name: 'Portador de Bilis',
    cost: 4,
    type: UnitType.AIR,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 720,
    damage: 68,
    speed: 1.6,
    range: 190,
    attackSpeed: 980,
    targetPref: TargetPreference.ANY,
    description: 'Zepelín biológico que suelta cápsulas ácidas en área. Castiga torres agrupadas; débil a fuego sostenido.',
    flavor: '“Flota como grasa ardiente, cae como granizo tóxico.”',
    count: 1,
    isAoE: true,
    aoeRadius: 65,
    shape: 'circle',
    color: '#9be48a',
    projectileType: 'missile'
  },
  {
    id: 'aracnid_web_launcher',
    name: 'Lanza-Redes',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 300,
    damage: 42,
    speed: 1.1,
    range: 180,
    attackSpeed: 1200,
    targetPref: TargetPreference.ANY,
    description: 'Dispara redes adhesivas que fijan blancos ligeros. Bastan chispas AOE o llamas para barrerlos.',
    flavor: '“La trampa es pegajosa; ellos, frágiles.”',
    count: 3,
    shape: 'hexagon',
    color: '#b6f0c2',
    projectileType: 'plasma'
  },
  {
    id: 'aracnid_acid_spine',
    name: 'Espina Ácida Balística',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 280,
    damage: 64,
    speed: 1,
    range: 210,
    attackSpeed: 1350,
    targetPref: TargetPreference.ANY,
    description: 'Proyectiles perforantes que dejan ácido residual. HP bajo: AOE ígneo o explosivo los neutraliza al instante.',
    flavor: '“Silba, atraviesa y deja humo verde.”',
    count: 3,
    shape: 'cross',
    color: '#8ddf9c',
    projectileType: 'beam'
  },
  {
    id: 'aracnid_reflective_carapace',
    name: 'Carapacho Colmena con Espinas Reflejantes',
    cost: 5,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 1200,
    damage: 68,
    speed: 0.9,
    range: 95,
    attackSpeed: 1200,
    targetPref: TargetPreference.ANY,
    description: 'Caparazón medio que devuelve astillas leves al contacto. Vulnerable a fuego continuo y AOE que limpie sus escoltas.',
    flavor: '“Un muro de espinas… que se chamusca rápido.”',
    count: 2,
    shape: 'circle',
    color: '#6ba86b',
    projectileType: 'none'
  },
  {
    id: 'aracnid_brood_nest',
    name: 'Nido Reproductor',
    cost: 4,
    type: UnitType.BUILDING,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 900,
    damage: 26,
    speed: 0,
    range: 140,
    attackSpeed: 1300,
    targetPref: TargetPreference.ANY,
    description: 'Genera crías y escupe ácido corto alcance. Fuego AOE limpia el enjambre y calcina el nido rápidamente.',
    flavor: '“Huevos, baba y una mecha corta.”',
    count: 1,
    shape: 'square',
    color: '#a6d38c',
    projectileType: 'plasma'
  },
  {
    id: 'aracnid_trap_web',
    name: 'Red Trampa de Zona',
    cost: 3,
    type: UnitType.BUILDING,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 620,
    damage: 18,
    speed: 0,
    range: 170,
    attackSpeed: 1250,
    targetPref: TargetPreference.ANY,
    description: 'Cubre un área con filamentos que ralentizan. Tiene poca resistencia y cae enseguida ante combustión o salpicadura AOE.',
    flavor: '“La trampa no arde… hasta que la prenden.”',
    count: 1,
    shape: 'triangle',
    color: '#c7f0a4',
    projectileType: 'plasma'
  },
  {
    id: 'aracnid_spore_rain',
    name: 'Lluvia de Esporas Lentas',
    cost: 3,
    type: UnitType.SPELL,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 1,
    damage: 60,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ANY,
    description: 'Nube de esporas que daña y reduce velocidad en área amplia. Una explosión o fuego limpia las esporas al toque.',
    flavor: '“Oscurece el cielo… hasta que alguien lo prende en fuego.”',
    count: 1,
    isAoE: true,
    aoeRadius: 170,
    shape: 'hexagon',
    color: '#d6ffb3',
    projectileType: 'beam'
  },
  {
    id: 'aracnid_pheromone_cloud',
    name: 'Nube de Feromonas Buff',
    cost: 2,
    type: UnitType.SPELL,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: 1,
    damage: -55,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ALLIES,
    description: 'Potencia ataque y coordinación de enjambres cercanos. Luz roja: fuego AOE disipará el aroma en segundos.',
    flavor: '“Huelen a victoria… y a queroseno ardiendo.”',
    count: 1,
    isAoE: true,
    aoeRadius: 150,
    shape: 'circle',
    color: '#e6ffcd',
    projectileType: 'none'
  },
  {
    id: 'aracno_spider_lethal',
    name: 'Araña Colmillo',
    cost: 1,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: ARACNO_SPIDER_MODES.lethal.hp,
    damage: ARACNO_SPIDER_MODES.lethal.damage,
    speed: ARACNO_SPIDER_MODES.lethal.speed,
    range: ARACNO_SPIDER_MODES.lethal.range,
    attackSpeed: ARACNO_SPIDER_MODES.lethal.attackSpeed,
    targetPref: ARACNO_SPIDER_MODES.lethal.targetPref,
    description: 'Versión de choque: muerde rápido y presiona defensas blandas para abrir paso al enjambre.',
    flavor: '“Si crujen, la colmena avanza.”',
    count: 1,
    shape: 'triangle',
    color: '#c7ff8a',
    projectileType: 'none',
    hidden: true
  },
  {
    id: 'aracno_spider_heal',
    name: 'Araña Médica',
    cost: 1,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: ARACNO_SPIDER_MODES.healing.hp,
    damage: ARACNO_SPIDER_MODES.healing.damage,
    speed: ARACNO_SPIDER_MODES.healing.speed,
    range: ARACNO_SPIDER_MODES.healing.range,
    attackSpeed: ARACNO_SPIDER_MODES.healing.attackSpeed,
    targetPref: ARACNO_SPIDER_MODES.healing.targetPref,
    description: 'Se aferra a aliados para segregar bioestimulantes y extender su vida en combate.',
    flavor: '“Su mordida escuece, pero solo para despertar a los tuyos.”',
    count: 1,
    shape: 'diamond',
    color: '#a5ffcf',
    projectileType: 'none',
    hidden: true
  },
  {
    id: 'aracno_spider_kami',
    name: 'Araña Kamikaze',
    cost: 1,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.ARACNID,
    hp: ARACNO_SPIDER_MODES.kamikaze.hp,
    damage: ARACNO_SPIDER_MODES.kamikaze.damage,
    speed: ARACNO_SPIDER_MODES.kamikaze.speed,
    range: ARACNO_SPIDER_MODES.kamikaze.range,
    attackSpeed: ARACNO_SPIDER_MODES.kamikaze.attackSpeed,
    targetPref: ARACNO_SPIDER_MODES.kamikaze.targetPref,
    description: 'Carga con glándulas volátiles y deja un veneno ardiente al explotar contra tropas enemigas.',
    flavor: '“Brilla, chisporrotea y deja la zona hirviendo.”',
    count: 1,
    dotDuration: ARACNO_SPIDER_MODES.kamikaze.dotDuration,
    shape: 'hexagon',
    color: '#e4ff7a',
    projectileType: 'plasma',
    hidden: true
  },
  {
    id: 'humanoid_psionic_disruptor',
    name: 'Disruptor Psiónico',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 420,
    damage: 46,
    speed: 1.4,
    range: 36,
    attackSpeed: 950,
    targetPref: TargetPreference.ANY,
    description: 'Descarga cortes mentales que desajustan formaciones, pero pierde control bajo daño cinético o ráfagas EMP.',
    flavor: '“Tu rabia es mi munición… hasta que me desconectas.”',
    count: 3,
    shape: 'triangle',
    color: '#9f5de2',
    projectileType: 'none'
  },
  {
    id: 'humanoid_vampiric_raider',
    name: 'Asaltante Vampírico',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 560,
    damage: 52,
    speed: 1.25,
    range: 32,
    attackSpeed: 1000,
    targetPref: TargetPreference.ANY,
    description: 'Drena vitalidad para extender combates, pero sus tejidos se rompen rápido ante impacto cinético y pulsos EMP.',
    flavor: '“Tu sangre retumba mejor que cualquier tambor de guerra.”',
    count: 2,
    shape: 'square',
    color: '#c43d6f',
    projectileType: 'none'
  },
  {
    id: 'humanoid_morale_controller',
    name: 'Controlador de Moral',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 500,
    damage: -40,
    speed: 1.15,
    range: 95,
    attackSpeed: 1250,
    targetPref: TargetPreference.ALLIES,
    description: 'Impulsa valor psiónico y desarma moraleja enemiga, pero su foco se rompe con proyectiles cinéticos y picos EMP.',
    flavor: '“No luchan por su bandera; luchan porque así lo ordeno.”',
    count: 1,
    isAoE: true,
    aoeRadius: 120,
    shape: 'diamond',
    color: '#7bcfa5',
    projectileType: 'none'
  },
  {
    id: 'humanoid_synaptic_marksman',
    name: 'Tirador de Rayos Sinápticos',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 380,
    damage: 70,
    speed: 1.3,
    range: 210,
    attackSpeed: 1150,
    targetPref: TargetPreference.ANY,
    description: 'Hazes enlazados que encadenan daño a distancia, pero un impacto cinético o EMP dispersa la sinapsis al instante.',
    flavor: '“Sigue el brillo; la corriente hace el resto.”',
    count: 2,
    shape: 'hexagon',
    color: '#70d1ff',
    projectileType: 'beam'
  },
  {
    id: 'humanoid_hover_lancer',
    name: 'Lancero Levitrón',
    cost: 3,
    type: UnitType.AIR,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 410,
    damage: 48,
    speed: 2.2,
    range: 180,
    attackSpeed: 900,
    targetPref: TargetPreference.ANY,
    description: 'Cabalga plataformas magnéticas y hostiga líneas largas. Frágil ante AA dedicada y haces concentrados.',
    flavor: '“No tocan el suelo; tampoco dejan descansar al enemigo.”',
    count: 2,
    shape: 'triangle',
    color: '#95c9ff',
    projectileType: 'laser'
  },
  {
    id: 'humanoid_void_bomber',
    name: 'Bombardero del Vacío',
    cost: 5,
    type: UnitType.AIR,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 820,
    damage: 82,
    speed: 1.8,
    range: 205,
    attackSpeed: 1100,
    targetPref: TargetPreference.ANY,
    description: 'Porta bombas gravitacionales que ralentizan al impactar. Excelente para romper pushes compactos.',
    flavor: '“Abren un micro-abismo y dejan caer la noche.”',
    count: 1,
    isAoE: true,
    aoeRadius: 60,
    shape: 'circle',
    color: '#7fb3ff',
    projectileType: 'missile'
  },
  {
    id: 'humanoid_fusion_orb_caster',
    name: 'Artífice de Orbes de Fusión',
    cost: 5,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 360,
    damage: 120,
    speed: 1.1,
    range: 190,
    attackSpeed: 1800,
    targetPref: TargetPreference.ANY,
    description: 'Lanza orbes de carga lenta que estallan en área; balas cinéticas y descargas EMP desestabilizan la reacción.',
    flavor: '“Si chispea, retrocede. Si zumba, corre.”',
    count: 1,
    isAoE: true,
    aoeRadius: 70,
    shape: 'cross',
    color: '#ffb347',
    projectileType: 'plasma'
  },
  {
    id: 'humanoid_psychic_bastion',
    name: 'Centurión de Escudo Psíquico',
    cost: 6,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 1600,
    damage: 78,
    speed: 0.75,
    range: 110,
    attackSpeed: 1250,
    targetPref: TargetPreference.ANY,
    description: 'Barrera mental que refleja daño ligero y sostiene la línea, pero colapsa si recibe ráfagas cinéticas o EMP sostenido.',
    flavor: '“La mente levanta muros; el plomo los derriba.”',
    count: 1,
    shape: 'circle',
    color: '#5ac1d6',
    projectileType: 'none'
  },
  {
    id: 'humanoid_psionic_pylon',
    name: 'Pilar Psiónico de Aura',
    cost: 4,
    type: UnitType.BUILDING,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 900,
    damage: 0,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ALLIES,
    description: 'Ancla de aura que acelera regeneración psíquica cercana; proyectiles cinéticos y pulsos EMP apagan su resonancia.',
    flavor: '“No es piedra: es voluntad solidificada.”',
    count: 1,
    shape: 'diamond',
    color: '#d4a5ff',
    projectileType: 'none'
  },
  {
    id: 'humanoid_adaptive_portal',
    name: 'Portal de Refuerzos Adaptativos',
    cost: 5,
    type: UnitType.BUILDING,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 820,
    damage: 52,
    speed: 0,
    range: 160,
    attackSpeed: 1200,
    targetPref: TargetPreference.ANY,
    description: 'Canaliza refuerzos y dispara descargas para cubrir la llegada; daño cinético y EMP desconfiguran la matriz de enlace.',
    flavor: '“Cada chispa abre un pasillo, salvo cuando el metal lo aplasta.”',
    count: 1,
    shape: 'square',
    color: '#7be0d8',
    projectileType: 'laser'
  },
  {
    id: 'humanoid_psychic_silence',
    name: 'Silencio Psíquico',
    cost: 3,
    type: UnitType.SPELL,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 1,
    damage: 0,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ANY,
    description: 'Apaga canales de habilidad en un área corta; defensas cinéticas o choques EMP quiebran el silencio prematuramente.',
    flavor: '“Calla, piensa, avanza.”',
    count: 1,
    isAoE: true,
    aoeRadius: 140,
    shape: 'hexagon',
    color: '#a0b8ff',
    projectileType: 'none'
  },
  {
    id: 'humanoid_fear_wave',
    name: 'Onda de Miedo',
    cost: 4,
    type: UnitType.SPELL,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.HUMANOID,
    hp: 1,
    damage: 80,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ANY,
    description: 'Desborda pánico que dispersa formaciones; balas cinéticas y pulsos EMP rompen la ola mental y reducen su impacto.',
    flavor: '“El miedo es contagioso… hasta que algo te despierta de golpe.”',
    count: 1,
    isAoE: true,
    aoeRadius: 190,
    shape: 'circle',
    color: '#ff9fb3',
    projectileType: 'beam'
  },
  {
    id: 'slimoid_mitosis_guardian',
    name: 'Guardián Mitótico',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    splitOnDeath: true,
    spawnChild: 'slimoid_adhesive_splitlings',
    hp: 980,
    damage: 56,
    speed: 1.05,
    range: 22,
    attackSpeed: 1100,
    targetPref: TargetPreference.ANY,
    description: 'Bloque de baba que se divide en dos enjambres al morir, sosteniendo línea mientras diluye fuego enemigo.',
    flavor: '“Córtalo y tendrás dos problemas pegajosos.”',
    count: 1,
    shape: 'circle',
    color: '#5fd8b8',
    projectileType: 'none'
  },
  {
    id: 'slimoid_adhesive_splitlings',
    name: 'Gotas Adhesivas',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 320,
    damage: 34,
    speed: 1.5,
    range: 20,
    attackSpeed: 900,
    targetPref: TargetPreference.ANY,
    description: 'Parejas de babas que ralentizan al golpear por pura adhesión. Se deslizan rápido pero caen con AOE ligero.',
    flavor: '“No te matan; te dejan pegado para que otros lo hagan.”',
    count: 2,
    shape: 'triangle',
    color: '#7af1c8',
    projectileType: 'none'
  },
  {
    id: 'slimoid_corrosive_striker',
    name: 'Zambullidor Corrosivo',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 540,
    damage: 64,
    speed: 1.35,
    range: 24,
    attackSpeed: 1000,
    targetPref: TargetPreference.ANY,
    description: 'Golpes saturados de enzimas que aflojan armaduras y derriten blindaje prolongado. Prefiere luchar en grupos.',
    flavor: '“Cada estocada deja olor a óxido verde.”',
    count: 2,
    shape: 'diamond',
    color: '#4fcaa8',
    projectileType: 'none'
  },
  {
    id: 'slimoid_arc_globber',
    name: 'Glóbulo en Arco',
    cost: 4,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 480,
    damage: 58,
    speed: 1.1,
    range: 210,
    attackSpeed: 1200,
    targetPref: TargetPreference.ANY,
    description: 'Lanza glóbulos ácidos en trayectoria parabólica que salpican a grupos compactos. Débil a fuego de represalia.',
    flavor: '“Lo verás venir… pero aún te mojará.”',
    count: 2,
    isAoE: true,
    aoeRadius: 60,
    shape: 'hexagon',
    color: '#6be6d2',
    projectileType: 'plasma'
  },
  {
    id: 'slimoid_cloud_skimmer',
    name: 'Planeador de Niebla',
    cost: 3,
    type: UnitType.AIR,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 380,
    damage: 40,
    speed: 2.3,
    range: 165,
    attackSpeed: 870,
    targetPref: TargetPreference.ANY,
    description: 'Globo viscoso que rocía ácido ligero y ralentiza al contacto. Ideal para hostigar sin exponerse.',
    flavor: '“Suficientemente ligero para flotar, suficientemente tóxico para doler.”',
    count: 3,
    shape: 'diamond',
    color: '#a7f7dd',
    projectileType: 'plasma'
  },
  {
    id: 'slimoid_vent_crawler',
    name: 'Rastrero de Ventosa',
    cost: 4,
    type: UnitType.AIR,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 690,
    damage: 66,
    speed: 1.7,
    range: 185,
    attackSpeed: 1000,
    targetPref: TargetPreference.ANY,
    description: 'Molde aéreo que se adhiere a torres y drena su integridad con pulsos. Débil a ráfagas de energía y AA.',
    flavor: '“Cuando se pega, es como arrancar alquitrán vivo.”',
    count: 1,
    isAoE: false,
    shape: 'hexagon',
    color: '#9adbc7',
    projectileType: 'beam'
  },
  {
    id: 'slimoid_pool_spitter',
    name: 'Escupidor de Charcos',
    cost: 3,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 420,
    damage: 48,
    speed: 1.05,
    range: 185,
    attackSpeed: 1050,
    targetPref: TargetPreference.ANY,
    description: 'Dispara proyectiles que explotan en un charco que deja DoT residual. Ideal contra empujes lentos.',
    flavor: '“Donde cae, la tierra burbujea.”',
    count: 2,
    isAoE: true,
    aoeRadius: 65,
    shape: 'cross',
    color: '#55d3bd',
    projectileType: 'beam'
  },
  {
    id: 'slimoid_absorbent_bulk',
    name: 'Masa Absorbente',
    cost: 5,
    type: UnitType.GROUND,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 1500,
    damage: 54,
    speed: 0.7,
    range: 90,
    attackSpeed: 1150,
    targetPref: TargetPreference.ANY,
    description: 'Tanque gelatinoso que acumula resistencias al recibir golpes y explota al morir, castigando el foco enemigo.',
    flavor: '“Golpéalo y solo se vuelve más denso.”',
    count: 1,
    isAoE: true,
    aoeRadius: 85,
    shape: 'square',
    color: '#3fb195',
    projectileType: 'none'
  },
  {
    id: 'slimoid_healing_pool',
    name: 'Charco Absorbente',
    cost: 4,
    type: UnitType.BUILDING,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 920,
    damage: -42,
    speed: 0,
    range: 160,
    attackSpeed: 1250,
    targetPref: TargetPreference.ALLIES,
    description: 'Estructura viscosa que cura y absorbe parte del daño entrante como vida temporal para aliados cercanos.',
    flavor: '“Pisa el charco; siente que el metal se repara.”',
    count: 1,
    isAoE: true,
    aoeRadius: 120,
    shape: 'circle',
    color: '#78f2d4',
    projectileType: 'none'
  },
  {
    id: 'slimoid_acid_vent',
    name: 'Géiser Ácido',
    cost: 5,
    type: UnitType.BUILDING,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 1100,
    damage: 62,
    speed: 0,
    range: 190,
    attackSpeed: 1050,
    targetPref: TargetPreference.ANY,
    description: 'Estructura que lanza chorros ácidos periódicos, negando zonas y empujes apretados. Requiere protección aérea.',
    flavor: '“Respira profundo y deja el aire quemando.”',
    count: 1,
    isAoE: true,
    aoeRadius: 70,
    shape: 'hexagon',
    color: '#64dec8',
    projectileType: 'plasma'
  },
  {
    id: 'slimoid_viscous_wave',
    name: 'Oleada Viscosa',
    cost: 3,
    type: UnitType.SPELL,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 1,
    damage: 70,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ANY,
    description: 'Ola espesa que empuja y desordena tropas, abriendo espacio antes de cruzar el puente.',
    flavor: '“Un golpe de baba que barre todo hacia atrás.”',
    count: 1,
    isAoE: true,
    aoeRadius: 150,
    shape: 'triangle',
    color: '#8ef1db',
    projectileType: 'none'
  },
  {
    id: 'slimoid_corrosive_shroud',
    name: 'Capa Corrosiva',
    cost: 4,
    type: UnitType.SPELL,
    faction: Faction.ALIEN,
    alienSubtype: AlienSubtype.SLIMOID,
    hp: 1,
    damage: 90,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    targetPref: TargetPreference.ANY,
    description: 'Neblina ácida que debuffea armaduras enemigas y deja un DoT breve. Ideal para iniciar focos en tanques rivales.',
    flavor: '“Es más liviana que el aire… y más pesada que el hierro.”',
    count: 1,
    isAoE: true,
    aoeRadius: 170,
    shape: 'diamond',
    color: '#9df7e6',
    projectileType: 'beam'
  }
];

export const CARD_LIBRARY: Card[] = CARD_SEEDS.map(card => ({
  ...card,
  visualFamily: card.visualFamily ?? VISUAL_FAMILY_BY_FACTION[card.faction],
  spellShape: card.type === UnitType.SPELL
    ? (card.spellShape ?? SPELL_SHAPES[card.id] ?? 'concentric')
    : undefined
}));

export const PLAYABLE_CARD_LIBRARY = CARD_LIBRARY.filter(card => !card.hidden);

export const CARD_DISTRIBUTION_SCHEMA = [
  {
    group: 'Humanos',
    faction: Faction.HUMAN,
    slots: { melee: 3, shooters: 2, tank: 1, structures: 2, spells: 2 }
  },
  {
    group: 'Androides',
    faction: Faction.ANDROID,
    slots: { melee: 3, shooters: 2, tank: 1, structures: 2, spells: 2 }
  },
  {
    group: 'Alien Humanoide',
    faction: Faction.ALIEN,
    subtype: AlienSubtype.HUMANOID,
    slots: { melee: 3, shooters: 2, tank: 1, structures: 2, spells: 2 }
  },
  {
    group: 'Alien Arácnido',
    faction: Faction.ALIEN,
    subtype: AlienSubtype.ARACNID,
    slots: { melee: 3, shooters: 2, tank: 1, structures: 2, spells: 2 }
  },
  {
    group: 'Alien Slimoide',
    faction: Faction.ALIEN,
    subtype: AlienSubtype.SLIMOID,
    slots: { melee: 3, shooters: 2, tank: 1, structures: 2, spells: 2 }
  }
] as const;

// TOP/BOTTOM lanes: inner towers now sit at x=220 (y offsets ±120) and outers at x=380 (y offsets ±180) to open extra space near the bridges.
export const INITIAL_TOWERS_PLAYER = [
  { type: TowerType.KING, x: 100, y: ARENA_HEIGHT / 2, hp: 2975, range: 330, damage: 130, lane: 'CENTER' },
  { type: TowerType.INNER, x: 220, y: ARENA_HEIGHT / 2 - 120, hp: 1530, range: 270, damage: 95, lane: 'TOP' },
  { type: TowerType.INNER, x: 220, y: ARENA_HEIGHT / 2 + 120, hp: 1530, range: 270, damage: 95, lane: 'BOTTOM' },
  { type: TowerType.OUTER, x: 380, y: ARENA_HEIGHT / 2 - 180, hp: 2040, range: 270, damage: 90, lane: 'TOP' },
  { type: TowerType.OUTER, x: 380, y: ARENA_HEIGHT / 2 + 180, hp: 2040, range: 270, damage: 90, lane: 'BOTTOM' },
];

export const INITIAL_TOWERS_AI = [
  { type: TowerType.KING, x: ARENA_WIDTH - 100, y: ARENA_HEIGHT / 2, hp: 2975, range: 330, damage: 130, lane: 'CENTER' },
  { type: TowerType.INNER, x: ARENA_WIDTH - 220, y: ARENA_HEIGHT / 2 - 120, hp: 1530, range: 270, damage: 95, lane: 'TOP' },
  { type: TowerType.INNER, x: ARENA_WIDTH - 220, y: ARENA_HEIGHT / 2 + 120, hp: 1530, range: 270, damage: 95, lane: 'BOTTOM' },
  { type: TowerType.OUTER, x: ARENA_WIDTH - 380, y: ARENA_HEIGHT / 2 - 180, hp: 2040, range: 270, damage: 90, lane: 'TOP' },
  { type: TowerType.OUTER, x: ARENA_WIDTH - 380, y: ARENA_HEIGHT / 2 + 180, hp: 2040, range: 270, damage: 90, lane: 'BOTTOM' },
];

const INNER_TOWER_HP = INITIAL_TOWERS_PLAYER.find(t => t.type === TowerType.INNER)?.hp || 0;
export const OUTER_TOWER_HP = INITIAL_TOWERS_PLAYER.find(t => t.type === TowerType.OUTER)?.hp || 0;
export const MOTHERSHIP_HP = Math.round(OUTER_TOWER_HP * MOTHERSHIP_BALANCE.hpRatioFromOuter);
export const ARACNO_HIVE_BALANCE = {
  hp: Math.round(INNER_TOWER_HP * 0.5),
  decayPerSecond: INNER_TOWER_HP * 0.5 / 30,
  spawnIntervalMs: 5000,
  relativePositionFromKing: { x: 140, y: 0 }
} as const;

export const ARACNO_HIVE_ABILITY_BALANCE = {
  cost: 5,
  cooldown: 28,
  defaultMode: 'lethal'
} as const;

const MORALE_BOOST_RADIUS = CARD_LIBRARY.find(card => card.id === 'healing_matrix')?.aoeRadius ?? 180;

export const MECHA_NEXODO_BALANCE = {
  activationCost: 6,
  extraHp: 720,
  laserTotalDamage: 260,
  laserDurationMs: 5000,
  laserCooldownMs: 3000,
  laserRange: Math.round(MORALE_BOOST_RADIUS * 0.75),
  laserColor: '#ff4bd8',
  shieldColor: '#63d6ff',
  frameColor: '#1d7eea'
} as const;

export const isMeleeSingleUnitCard = (card: Card) =>
  card.type !== UnitType.SPELL && card.count === 1 && card.projectileType === 'none';

const MECHA_PILOT_CANDIDATES = PLAYABLE_CARD_LIBRARY.filter(isMeleeSingleUnitCard);

export const SPECIAL_ABILITIES: SpecialAbilityBlueprint[] = [
  {
    id: 'emp_overwatch',
    name: 'Pulso EMP de Saturación',
    badge: 'Control',
    description: 'Desactiva unidades robóticas y ralentiza sistemas durante una ventana crítica.',
    cost: EMP_ABILITY_BALANCE.cost,
    cooldown: Math.floor(EMP_ABILITY_BALANCE.cooldownMs / 1000),
    options: [
      {
        key: 'mode',
        label: 'Modo del pulso',
        description: 'Alterna entre aturdimiento completo o disrupción con daño.',
        type: 'select',
        choices: [
          { 
            value: EMP_ABILITY_BALANCE.modes.lockdown.key, 
            label: EMP_ABILITY_BALANCE.modes.lockdown.label, 
            hint: `${EMP_ABILITY_BALANCE.modes.lockdown.stunDuration / 1000}s de aturdimiento, sin daño`
          },
          { 
            value: EMP_ABILITY_BALANCE.modes.disruptor.key, 
            label: EMP_ABILITY_BALANCE.modes.disruptor.label, 
            hint: `${EMP_ABILITY_BALANCE.modes.disruptor.stunDuration / 1000}s + ${EMP_ABILITY_BALANCE.modes.disruptor.damage} daño`
          }
        ],
        defaultValue: EMP_ABILITY_BALANCE.defaultMode
      }
    ]
  },
  {
    id: 'mothership_command',
    name: 'Llamado de Nave Nodriza',
    badge: 'Apoyo',
    description: 'Despliega una nave insignia lenta con tropas embarcadas para abrir camino.',
    cost: MOTHERSHIP_BALANCE.cost,
    cooldown: Math.floor(MOTHERSHIP_BALANCE.baseCooldownMs / 1000),
    options: [
      {
        key: 'hangarUnit',
        label: 'Carga de Hangar',
        description: 'Tropa embarcada que se despliega junto a la nave insignia.',
        type: 'select',
        choices: PLAYABLE_CARD_LIBRARY
          .filter(c => c.type !== UnitType.SPELL)
          .map(c => ({
            value: c.id,
            label: `${c.name} · ${c.cost}⚡`,
            hint: c.description
          })),
        defaultValue: PLAYABLE_CARD_LIBRARY.find(c => c.type !== UnitType.SPELL)?.id
      }
    ]
  },
  {
    id: 'mecha_nexodo',
    name: 'Mecha Nexodo',
    badge: 'Asalto',
    description: 'Un mecha pilotado que alterna entre escudo brutal o un láser de daño constante.',
    cost: MECHA_NEXODO_BALANCE.activationCost,
    cooldown: Math.floor(MECHA_NEXODO_BALANCE.laserCooldownMs / 1000),
    options: [
      {
        key: 'mode',
        label: 'Modo de combate',
        description: 'Define si prioriza supervivencia o presión constante.',
        type: 'select',
        choices: [
          { value: 'shield', label: 'Escudo', hint: `Blindaje pesado: +${MECHA_NEXODO_BALANCE.extraHp} HP fijos para absorber focus.` },
          { value: 'laser', label: 'Láser', hint: `Rayo continuo: ${MECHA_NEXODO_BALANCE.laserTotalDamage} daño total (${MECHA_NEXODO_BALANCE.laserTotalDamage / (MECHA_NEXODO_BALANCE.laserDurationMs / 1000)} DPS) durante ${MECHA_NEXODO_BALANCE.laserDurationMs / 1000}s (CD ${MECHA_NEXODO_BALANCE.laserCooldownMs / 1000}s).` }
        ],
        defaultValue: 'shield'
      },
      {
        key: 'pilotCard',
        label: 'Piloto de mecha',
        description: 'Carta melee individual que sincroniza el comportamiento del mecha.',
        type: 'select',
        choices: MECHA_PILOT_CANDIDATES.map(card => ({
          value: card.id,
          label: `${card.name} · ${card.cost}⚡`,
          hint: card.description
        })),
        defaultValue: MECHA_PILOT_CANDIDATES[0]?.id
      }
    ]
  },
  {
    id: 'aracno_hive',
    name: 'Nido Aracno',
    badge: 'Enjambre',
    description: 'Estructura temporal que ancla un enjambre de arañas con rol configurable.',
    cost: ARACNO_HIVE_ABILITY_BALANCE.cost,
    cooldown: ARACNO_HIVE_ABILITY_BALANCE.cooldown,
    options: [
      {
        key: 'mode',
        label: 'Rol del enjambre',
        description: 'Define el tipo de araña que incubará el nido.',
        type: 'select',
        choices: [
          { value: 'lethal', label: 'Letal', hint: 'Daño directo contra tropas y defensas.' },
          { value: 'healing', label: 'Sanadora', hint: 'Cicatriza aliados cercanos mordiendo suave.' },
          { value: 'kamikaze', label: 'Kamikaze', hint: 'Impacto con veneno de daño en el tiempo.' }
        ],
        defaultValue: ARACNO_HIVE_ABILITY_BALANCE.defaultMode,
        lockDefault: true
      }
    ]
  }
];

export const createDefaultAbilityConfig = (ability: SpecialAbilityBlueprint) => ability.options.reduce((config, option) => {
  let defaultValue = option.defaultValue;

  if (defaultValue === undefined) {
    if (option.type === 'select' && option.choices?.length) defaultValue = option.choices[0].value;
    if (option.type === 'slider' && option.min !== undefined) defaultValue = option.min;
    if (option.type === 'toggle') defaultValue = false;
  }

  return { ...config, [option.key]: defaultValue ?? '' };
}, {} as Record<string, string | number | boolean>);

export const findAbilityById = (id: string) => SPECIAL_ABILITIES.find(a => a.id === id);
